### ISSUE TITLE
CMake Error at CMakeLists.txt:99 (find_package)

### ISSUE THREAD

**Issue by benjifriedman** [lostjared/glitch.gui#1]
Hi, I'm on mac OS Sonoma. After making the build folder and trying to run cmake, I get this error:

`-- The CXX compiler identification is AppleClang 15.0.0.15000100
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build configuration is: Release
-- is the C++ compiler loaded? 1
-- The C++ Compiler ID is: AppleClang
-- The C++ Compiler Version: 15.0.0.15000100
CMake Error at CMakeLists.txt:99 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!`

**Comment by lostjared** [comment]
Do you have OpenCV 4 installed with homebrew?

**Comment by lostjared** [comment]
watch this video: https://youtu.be/NUDnHnl1Arc

**Comment by lostjared** [comment]
I made you a tutorial on how to compile and install on Sonoma. https://youtu.be/LVwgHE24NkY

**Comment by benjifriedman** [comment]
Thanks, I was able to get further in the process, right before being able to open the program. I started a new issue with the error log I got when trying to run the program
